export { assetService } from '@/entities/asset/api/asset-service'
export { ASSET_CATEGORY_LABELS, ASSET_STATUS_LABELS } from '@/entities/asset/model/asset-constants'
export type { Asset, AssetCategory, AssetStatus } from '@/entities/asset/model/asset-types'
export { AssetCard } from '@/entities/asset/ui/asset-card'
export { AssetCategoryBadge } from '@/entities/asset/ui/asset-category-badge'
export { AssetStatusBadge } from '@/entities/asset/ui/asset-status-badge'
