/** CSS custom property names — color SoT is globals.css */
export const CSS_VAR = {
  background: '--background',
  foreground: '--foreground',
  card: '--card',
  cardForeground: '--card-foreground',
  popover: '--popover',
  popoverForeground: '--popover-foreground',
  primary: '--primary',
  primaryForeground: '--primary-foreground',
  primaryHover: '--primary-hover',
  primaryMuted: '--primary-muted',
  primaryMutedForeground: '--primary-muted-foreground',
  secondary: '--secondary',
  secondaryForeground: '--secondary-foreground',
  muted: '--muted',
  mutedForeground: '--muted-foreground',
  accent: '--accent',
  accentForeground: '--accent-foreground',
  destructive: '--destructive',
  destructiveForeground: '--destructive-foreground',
  border: '--border',
  input: '--input',
  ring: '--ring',
  sidebar: '--sidebar',
  sidebarForeground: '--sidebar-foreground',
  sidebarMuted: '--sidebar-muted',
  sidebarAccent: '--sidebar-accent',
  sidebarAccentForeground: '--sidebar-accent-foreground',
  sidebarPrimary: '--sidebar-primary',
  sidebarPrimaryForeground: '--sidebar-primary-foreground',
  sidebarBorder: '--sidebar-border',
  sidebarRing: '--sidebar-ring',
  success: '--success',
  successForeground: '--success-foreground',
  successMuted: '--success-muted',
  warning: '--warning',
  warningForeground: '--warning-foreground',
  warningMuted: '--warning-muted',
  danger: '--danger',
  dangerForeground: '--danger-foreground',
  dangerMuted: '--danger-muted',
  info: '--info',
  infoForeground: '--info-foreground',
  infoMuted: '--info-muted',
  chart1: '--chart-1',
  chart2: '--chart-2',
  chart3: '--chart-3',
  chart4: '--chart-4',
  chart5: '--chart-5',
  surfacePopover: '--surface-popover',
  surfacePopoverForeground: '--surface-popover-foreground',
  surfaceDialog: '--surface-dialog',
  surfaceSheet: '--surface-sheet',
} as const

/** Read an RGB-channel CSS variable as `rgb(r g b)` for canvas/SVG inline use */
export function cssVarRgb(name: keyof typeof CSS_VAR): string {
  return `rgb(var(${CSS_VAR[name]}))`
}
