export const APP_ROUTES = {
  login: '/login',
  dashboard: '/',
  projects: '/projects',
  projectDetail: '/projects/:projectId',
  assetNew: '/assets/new',
  assetDetail: '/assets/:assetId',
  search: '/search',
  aiExtension: '/ai-extension',
  devpilot: '/devpilot',
  settings: '/settings',
  settingsAccessControl: '/settings/access-control',
  settingsOperations: '/settings/operations',
  schedule: '/schedule',
  scheduleEdit: '/schedule/:weekId/:type',
  operationsWorkload: '/operations/workload',
  operationsApprovals: '/operations/approvals',
  operationsProfit: '/operations/profit',
  operationsReport: '/operations/report',
} as const
