export { projectService } from '@/entities/project/api/project-service'
export type { Project, ProjectLinks, ProjectStatus } from '@/entities/project/model/project-types'
export { PROJECT_STATUS_LABELS } from '@/entities/project/model/project-constants'
export { ProjectCard } from '@/entities/project/ui/project-card'
export { ProjectStatusBadge } from '@/entities/project/ui/project-status-badge'
